- name: Get evs_id
  include: lookup.yml
  when:
    - evs_name is defined

- name: Send request to API (create EVS)
  uri:
    url: "{{ AUTH_URL_EVS }}/cloudvolumes"
    method: POST
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  register: evs
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: evs.status == 200
  changed_when: false
  when:
    - evs_name is defined
    - not evs_id or evs_id is undefined

- debug:
    msg: "{{ evs }}"
