- name: Get evs_id
  include: lookup.yml
  when:
    - evs_name is defined

- name: Send request to API (create EVS)
  uri:
    url: "{{ AUTH_URL_EVS }}/cloudvolumes"
    method: POST
    body_format: raw
    return_content: true
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  register: evs
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: evs.status == 200
  changed_when: false
  when:
    - evs_name is defined
    - not evs_id or evs_id is undefined

- debug:
    msg: "{{ evs }}"

- name: Request job status from API (waiting for SUCCESS)
  uri:
    url: "{{ AUTH_URL_EVSv1 }}/{{ PROJECT_ID }}/jobs/{{ evs.json.job_id }}"
    method: GET
    return_content: true
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: jobstatus
  retries: 100
  delay: 5
  until: jobstatus.json.status == 'SUCCESS'
  changed_when: false
  when:
    - evs.json.job_id is defined
    - waitfor | bool
