- name: Send request to API (list evs for lookup)
  uri:
    url: "{{ AUTH_URL_EVS }}/cloudvolumes"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: evs_result
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: evs_result.status == 200
  changed_when: false
  when: evs_name is defined

- name: Set fact evs_id if evs_name is defined
  set_fact:
    evs_id: "{{ (evs_result.content|from_json)|json_query(\"volumes[?name=='\" + evs_name + \"'].id|[0]\") }}"
  when: evs_name is defined
