- name: Lookup evs_id
  include: lookup.yml

- name: Send request to API (show EVS)
  uri:
    url: "{{ AUTH_URL_EVS }}/volumes/{{ evs_id }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: volume
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: volume.status == 200
  changed_when: false

- debug:
    msg: "{{ volume.json }}"
